
# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1106
#  freemarker:
#    suffix: .ftl

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 下面可以指定xml文件中返回的实体类的位置，不指定的话需要使用全限定类名
#  type-aliases-package: com.example.demo.model
server:
  port: 9000